blank_issues_enabled: true
contact_links:
  - name: General Question or Discussion
    url: https://github.com/mmax120/skills-expand-your-team-with-copilot/discussions
    about: For questions, ideas, or discussions that don't fit the templates above
